# Generated by Django 4.2.2 on 2023-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='placeholder',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='projects',
            field=models.ManyToManyField(to='users.project'),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='documents',
            field=models.ManyToManyField(to='users.document'),
        ),
    ]
