# Generated by Django 4.2.2 on 2023-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_document_project_remove_placeholder_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='projects',
            new_name='project',
        ),
    ]
