# Generated by Django 4.2.2 on 2023-06-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_projects_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.FileField(default='templates/BOJ Form 1_Template.docx', upload_to='templates/'),
        ),
    ]
