# Generated by Django 4.2.2 on 2023-06-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinput_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='placeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.placeholder'),
        ),
    ]
